export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SHOW_PRODUCT_INFO = "SHOW_PRODUCT_INFO";
export const CHANGE_NUMBER_PRODUCT_CART = "CHANGE_NUMBER_PRODUCT_CART";
